### PR TITLE
Possibility to see who unlocked the door 

### PR DESCRIPTION
**Pull request by mansica**
I have added app settings, a capability and a flow trigger to enable who has unlocked the door.
The idea is to map a key and/or tag index with a name under the app settings. This will be read when the door unlocks and also trigger a flow with the unlocking user as a token.

### CODE REVIEW

**Comment by juw2** [comment]
Hi Mansica.
I have tried your modified app.
According to the documentation for the new z-wave card for ID Lock 150 the RFID numbers starts at 10 and for user pin it starts at 60.
But you only allow to add numbers 1-9.
This is user 9 at my lock:

"Node[160]: [COMMAND_CLASS_NOTIFICATION] {"V1 Alarm Type (Raw)":{"type":"Buffer","data":[0]},"V1 Alarm Type":0,"V1 Alarm Level (Raw)":{"type":"Buffer","data":[0]},"V1 Alarm Level":0,"Reserved (Raw)":{"type":"Buffer","data":[0]},"Notification Status (Raw)":{"type":"Buffer","data":[255]},"Notification Status":"On","Notification Type (Raw)":{"type":"Buffer","data":[6]},"Notification Type":"Access Control","Event (Raw)":{"type":"Buffer","data":[6]},"Event":6,"Properties1 (Raw)":{"type":"Buffer","data":[1]},"Properties1":{"Event Parameters Length":1,"Sequence":false},"Event Parameter":{"type":"Buffer","data":[68]},"Event (Parsed)":"Keypad Unlock Operation"}"

Data for that user is 68.
User pin 2 is 61

For RFID card 1:
"Node[160]: [COMMAND_CLASS_NOTIFICATION] {"V1 Alarm Type (Raw)":{"type":"Buffer","data":[0]},"V1 Alarm Type":0,"V1 Alarm Level (Raw)":{"type":"Buffer","data":[0]},"V1 Alarm Level":0,"Reserved (Raw)":{"type":"Buffer","data":[0]},"Notification Status (Raw)":{"type":"Buffer","data":[255]},"Notification Status":"On","Notification Type (Raw)":{"type":"Buffer","data":[6]},"Notification Type":"Access Control","Event (Raw)":{"type":"Buffer","data":[4]},"Event":4,"Properties1 (Raw)":{"type":"Buffer","data":[1]},"Properties1":{"Event Parameters Length":1,"Sequence":false},"Event Parameter":{"type":"Buffer","data":[10]},"Event (Parsed)":"RF Unlock Operation"}"

Data for that card is 10.

So, would it be possible to do a translation in the background like for user pin 60 transforms into 1, 61 into 2 etc. and for RFID 10 is 1 and 11 is 2 etc.

Or just open up so its possible to add 2 digit input in app settings.

Nice work by the way.

Br
Jonas

**Comment by mansica** [comment]
Hello Jonas!

According to the spec it only allows rfid between 10-19, 20-59 is reserved. 



Regarding the translation this is already there. What I wanted was to map the same code as you assign when adding a key code or rfid. They are between 1-9. So if you are unlocking with a rfid i’m subtracting 9 from the response and 59 respectively when using a key code.

                        let keyType = parseInt(report['Event Parameter'][0])
                        let keyId = keyType-59
.
.
.
                        let tagId = parseInt(report['Event Parameter'][0])-9

Glad you tried it out and enjoyed it.

Best regards
/Mats

**Comment by juw2** [comment]
Do you have the lock yourself?
One function that I'm missing is that I would like to trigger flows when you the lock is put in away mode from the outside. The it would be possible to activate the alarm for instance.
The function I mean is when you lock the door and than add a pin and then press # instead of unlock with *. In this mode it's not possible to open the lock from the inside. With the button.
Would that be possible to add as well?
A flow card in When...  A lock just locked in Away mode

Br
Jonas

**Comment by juw2** [comment]
Hi, have done som tests now with Away mode and this is what my lock reports in both developer page and node.js in debug mode. Adding a file with the data. Have tried 4 times and it reports the same every time.

[IDLock Away Mode.txt](https://github.com/TedTolboom/no.IDLock/files/2383528/IDLock.Away.Mode.txt)

**Comment by TedTolboom** [comment]
@mansica great work, thanks!.
I'll merge the PR into the development branch.

Can you send me your name and mail address so I can add you as contributor?

**Pull request merged**
